workflows:
  version: 2
  test-supported-versions:
    jobs:
      - test-mattermost-3.10
      - test-mattermost-4.0
      - test-mattermost-4.1
 
version: 2
jobs:
  test-mattermost-base: &test-mattermost-base
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: for i in 1 2 3 4 5 6 7 8 9 10; do curl -I "${MATTERMOST_URL:-http://localhost:8065}" || sleep 10 && continue; break; done
      - run: mvn integration-test
  test-mattermost-3.10:
    <<: *test-mattermost-base
    docker:
      - image: circleci/openjdk:8-jdk
      - image: mattermost/mattermost-preview:3.10
  test-mattermost-4.0:
    <<: *test-mattermost-base
    docker:
      - image: circleci/openjdk:8-jdk
      - image: mattermost/mattermost-preview:4.0
